# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# adding font awesome
gems:
  - jekyll-font-awesome-sass

# Site title
title: "Seth Barker"

# A description of your site for meta tag, search engine results.
description: "Welcome to my site which will be used to post personal interest articles. For now, navigate to the 'About Me' page to learn more about the author!"


# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://sethbarker.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-9NS91NVL6P"

# Site navigation - each item must have a title and a url.
# navigation:
navigation:
  - text: Home
    url: /
  - text: About Me
    url: /about
  - text: Articles
    url: /articles
    
# The shortname for your Disqus site to enable comments.
disqus: sethbarker

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true
  

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
  
# Theme
remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme
